### ISSUE TITLE
cal.parse('2015-11-18') returns November 19th 2015

### ISSUE THREAD

**Issue by simonw** [bear/parsedatetime#145]
I'm not sure if this is intended behavior, but I found this very confusing:

    >>> import parsedatetime
    >>> cal = parsedatetime.Calendar()
    >>> cal.parse('2015-11-18')
    ((2015, 11, 19, 20, 15, 0, 3, 323, 0), 2)

Is this a bug in the library, or am I misunderstanding something about how this function should be used? Is there an alternative way to use this library that would result in "2015-11-18" coming out as Nov 18th (not November 19th).

**Comment by bear** [comment]
I believe you are hitting issue #133 which we have fixed in the master branch but not yet release as we are pushing to release on both v2.7 and v3.5 for python support

>>> import parsedatetime
>>> parsedatetime.__version__
u'2.0'
>>> c = parsedatetime.Calendar()
>>> c.parse('2015-11-18')
(time.struct_time(tm_year=2015, tm_mon=11, tm_mday=18, tm_hour=17, tm_min=50, tm_sec=21, tm_wday=3, tm_yday=323, tm_isdst=0), 1)

you will also notice that the returned datetime is struct_time value and not just a tuple

**Comment by simonw** [comment]
Confirmed, this bug is fixed in master. Thanks for the quick reply!
