### ISSUE TITLE
Relative times containing years fail when computed from a leap day

### ISSUE THREAD

**Issue by schoen** [bear/parsedatetime#155]
When it is February 29 (like today!), `parsedatetime.Calendar().parse("1 year")` raises

`ValueError: day is out of range for month`

(It's trying to find February 29 in the following non-leap year, i.e., February 29, 2017.)

I think this is unexpected behavior because people would expect to be able to specify relative time intervals in terms of years on any day. (For example, we had written code that always computes `parse("1 year")` relative to the present day, and it crashes when run today!)

**Comment by idpaterson** [comment]
I'm getting Feb 28, 2017 – are you using a specific version, or master?

**Comment by schoen** [comment]
@idpaterson, 1.5 from PyPi.

**Comment by bear** [comment]
Last week I was thinking we should push a new version...

**Comment by mistercrunch** [comment]
+1 just hit this problem today

**Comment by mistercrunch** [comment]
It this fixed in `master` ?

**Comment by idpaterson** [comment]
@mistercrunch there are _a lot_ of changes in master, so that's probably not going to happen today but I'm glad to hear that it's on your mind, @bear!

**Comment by mistercrunch** [comment]
Maybe cherry pick the commit that fixes this and push a hotfix to pypi?

**Comment by mistercrunch** [comment]
It `master` stable? I was going to install it on my production boxes.

**Comment by idpaterson** [comment]
It must have been an incidental fix; there are no commit messages, comments, or test cases specifically addressing the leap day. A pull request against master may be appropriate if anyone affected has time to find and patch the issue.

I have been using parsedatetime master in production on [an Alfred workflow](https://github.com/idpaterson/alfred-wunderlist-workflow) since Feb 2015 with no problems (primarily using `parse` and `nlp` against today-relative user input dates) currently up-to-date with the latest master. The test coverage is excellent though datetime-related edge cases are inherently difficult to identify and test.

**Comment by bear** [comment]
I can push a version now if that is needed.

**Comment by bear** [comment]
v2.0 has been released

**Comment by mistercrunch** [comment]
@bear saves the day.  See you in 4 years!

**Comment by bear** [comment]
:+1:

**Comment by schoen** [comment]
@bear, thanks for the new release. I agree it fixes this problem, although please also see #156 because our project hopes to support Python 2.6 (which has a problem with 2.0).

**Comment by bear** [comment]
@schoen I will look at that now

**Comment by mistercrunch** [comment]
@schoen , many libs are dropping support for `2.6`, you should consider moving up to `2.7` or go straight to `3.4`
