### ISSUE TITLE
Incorrect dates

### ISSUE THREAD

**Issue by joshtronic** [bear/parsedatetime#30]
I've been noticing some issues when using strings like "Third Monday in January 2013" as well as using offsets with strings like this "Fourth Thursday in November 2013 +1 day"

Here's some examples:

String -- parsedatetime return -- expected return
Last Monday of January 2013 -- 2013-01-19 -- 2013-01-28
First Monday of January 2013 -- 2013-01-26 -- 2013-01-07
First Monday of September 2013 -- 2013-09-26 - 2013-09-02
First Monday of September 2013 +6 days -- 2013-09-30 - 2013-09-08

**Comment by bear** [comment]
I don't think the parse() function will ever parse this correctly but thanks to the new nlp() routine you can get that string parsed into two results which could be further merged or processed:

nlp('Last Monday of January 2013')

    ((datetime.datetime(2015, 6, 29, 9, 0), 1, 0, 11, 'Last Monday'), (datetime.datetime(2013, 1, 1, 13, 51, 20), 1, 14, 27, ' January 2013'))

So nlp() has split the string into two date parts and includes what portion is tied to what -- still not perfect I admit.

If this is still an issue then please ping me so we can re-word the issue so that @geoffreyfloyd can see if the nlp() function could handle it.
