### ISSUE TITLE
Hours/Minutes parsing error

### ISSUE THREAD

**Issue by Enissay** [bear/parsedatetime#31]
Hi,

The code is working fine for my use, but I noticed some differences in hours/minutes between the input and the result.

```
result = p.parse("Tomorrow 09h12")
print(result[0])
>>> time.struct_time(tm_year=2014, tm_mon=1, tm_mday=13, tm_hour=18, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=13, tm_isdst=-1)
```
and 
```
result = p.parse("06/01/2014 09h12")
print(result[0])
>>> time.struct_time(tm_year=2014, tm_mon=6, tm_mday=1, tm_hour=10, tm_min=48, tm_sec=41, tm_wday=6, tm_yday=152, tm_isdst=-1)
```
In the two examples I kept the same "09h12" and I've got different results... What am I missing ?

Thanks in advance

**Comment by bear** [comment]
k, this is now working as intended because of two things - the 09h12 part is properly being ignored for Tomorrow parsing as it's not a modifier linked to Tomorrow and also because of the reason it's being ignored for the "06/01/2014" part - the "12" causes the "9h" to not be parsed (correctly) so it's also ignored.

Going to mark this as working as planned.
