### ISSUE TITLE
Parse as according to level of granularity

### ISSUE THREAD

**Issue by maebert** [bear/parsedatetime#32]
Hi, quick question: I basically want to parse date ranges given as `from` and `until`, e.g. `from = 'jan 2013'` and `until = 'dec 2013'`. In that case I would like to get from resolved to Jan 1, 2013 00:00 and until to Dec 31, 2013 23:59. Likewise, "today" should be parsed as 00:00 of today if parsing for `from` (backwards inclusive), and 23:59 of today if parsing for `to` (forward inclusive). Any way to achieve that with parsedatetime? 

I digged into the code, what I'd really need is knowing what level of detail the string had (is it a day? a week? a month?  a year?) when it comes back from `parse(...)`. Ideas?

**Comment by bear** [comment]
sheesh - another bug that has sat unanswered - my apologies for not doing this sooner...

The purpose of the second parameter to parse is to allow you to specify a starting date/time so what I often will do to solve your issue is call parse with today's date but with the time set to 1am.

This will let you compare the time tuple that parse() returns to your known 1am and then you can see if it's the date or the time being modfied - that will let you know what type of date/time was parsed.

again, apologies for not replying sooner.
