### ISSUE TITLE
Wrong Parse for specific date formats

### ISSUE THREAD

**Issue by pratikpoddar** [bear/parsedatetime#33]
Really appreciate if you could please help me add the code to parse the following date formats as well:

cal.parse('4 February 2014 18.33 GMT')
cal.parse('2014-02-03T14:01:04-08:00')

Thanks a lot

**Comment by idpaterson** [comment]
To shed a bit of light on what is happening here, *Tuesday 9/16* is interpreted as Sep 16 *plus* the number of days between now and the next Tuesday. A possible solution might be to allow weekday names in date formats but computationally ignore them (if you say the 15th is a Tuesday, we'll take your word for it).

**Comment by bear** [comment]
The first example is parsing properly except for the timezone part which .parse() will always ignore as timezones are messy enough that parsedatetime has always assumed that the '''start''' parameter to parse() will have the proper TZ set.

The second example won't be handled by parse() as parse() ignores all of the normal computer date formats because they are just that, computer dates and not human dates.
