### ISSUE TITLE
Hour:25AM/PM not being parsed.

### ISSUE THREAD

**Issue by webgovernor** [bear/parsedatetime#36]
Hello,

```python
>>> cal.parse('March 14th 8am')
((2014, 3, 14, 8, 0, 0, 2, 71, 1), 3)
>>> cal.parse('March 14th 8:00am')
((2014, 3, 8, 0, 0, 0, 2, 71, 1), 3)
>>> cal.parse('March 14th 8:15am')
((2014, 3, 8, 15, 0, 0, 2, 71, 1), 3)
>>> cal.parse('March 14th 8:24am')
((2014, 3, 8, 0, 0, 0, 2, 71, 1), 3)
```

But changing that to anything greater than `8:24am` prevents the string from being parsed.

```python
>>> cal.parse('March 14th 8:30am')
(time.struct_time(tm_year=2014, tm_mon=3, tm_mday=12, tm_hour=18, tm_min=10, tm_sec=44, tm_wday=2, tm_yday=71, tm_isdst=1), 0)
```

**Comment by MatthiasKauer** [comment]
Testing around, I observe that "8:24am" isn't parsed on my system. It just puts the current time there. "8:30 am" (with space) works however.

**Comment by idpaterson** [comment]
This one seemed pretty curious so I took a look as well. RE_DATE3 was matching `March 14th 8` as the date leaving `:30` for something else to parse. It was being a bit too greedy, the 8 was parsing as a day of the month in the same way that 14th was.

I think that the best way to avoid consuming the time here is to assert that what we think is the day of the month is not followed by a colon, am, or pm. Those are localized things so while the original regex included `am|pm` it's best to use the locale
```python
self.RE_DATE3 = r'''(?P<date>
                        (?:
                            (?:^|\s)
                            (?P<mthname>
                                {months}|{shortmonths}
                            )\b
                            |
                            (?:^|\s)
                            (?P<day>[1-9]|[012]\d|3[01])
                            (?P<suffix>{daysuffix}|)
                            (?!{timeseperator}|{meridian})\b
                            |
                            (?:,\s|\s)
                            (?P<year>\d\d(?:\d\d|))
                            (?!{timeseperator}|{meridian})\b
                        ){{1,3}}
                        (?(mthname)|$-^)
                    )'''.format(**self.locale.re_values)
```

The main difference is that the assertion `(?!{timeseperator}|{meridian})\b` is used rather than the original `(?!\d|am|pm)`. It has also been added after the year since 2-digit times will match the year regex.

When I have a moment this weekend I will add your examples as test cases, clean up some of the slightly odd syntax in the regex, and push out a commit with this change.

**Comment by idpaterson** [comment]
There might be some issues with that approach for locales that do not define `meridian`, if the assertion resolves to something like `(?!:|)` then this approach won't work because that empty assertion guarantees a failed match. Will need some tweaks and testing in those locales as well.

**Comment by idpaterson** [comment]
2e0cd8a12c1daee11e16d506e2990f0a099a8103 adopts the approach outlined above with handling for non-meridian locales by creating a `timecomponents` value and using `(?!\s*(?:{timecomponents}))` rather than hardcoding the alternation between timeseparator and the potentially-empty meridian. Test cases have been added for the cases that did not parse properly before this change.
