### ISSUE TITLE
Parse words to numbers (thirteen => 13)

### ISSUE THREAD

**Issue by plajjan** [bear/parsedatetime#56]
Noticed we can't parse "in two years"... https://github.com/bear/parsedatetime/blob/master/implementation_notes.txt mentions it can be pretty tricky. I found https://github.com/ghewgill/text2num/blob/master/text2num.py which seems to be doing a decent job, would you consider including that?

**Comment by idpaterson** [comment]
This is supported for English language numbers up to and including twenty. After that it would get tricky since numbers may be expressed in multiple words. For larger numbers, it looks like parsedatetime has the text2num logic incorporated in the `_convertUnitAsWords` function, but that function is not actually used anywhere.

It would probably be possibly to parse those multi-word numbers but likely not worth the effort. Except in limited circumstances I would imagine that spelling out numbers higher than twenty is very rare.

**Comment by plajjan** [comment]
I'm sorry, I realize that my problem lies with an older version of parsedatetime that ships with Ubuntu 14.04. Using the latest from pypi does correctly parse words, like "three months";

Old version in Ubuntu 14.04:
```
>>> pdt.parse("3 months")
(time.struct_time(tm_year=2015, tm_mon=8, tm_mday=25, tm_hour=8, tm_min=3, tm_sec=37, tm_wday=1, tm_yday=237, tm_isdst=-1), 1)
>>> pdt.parse("three months")
(time.struct_time(tm_year=2015, tm_mon=6, tm_mday=4, tm_hour=8, tm_min=3, tm_sec=38, tm_wday=3, tm_yday=155, tm_isdst=-1), 1)
>>> 
```

Latest pypi:
```
>>> pdt.parse("3 months")
(time.struct_time(tm_year=2015, tm_mon=8, tm_mday=25, tm_hour=8, tm_min=2, tm_sec=29, tm_wday=1, tm_yday=237, tm_isdst=-1), 1)
>>> pdt.parse("three months")
(time.struct_time(tm_year=2015, tm_mon=8, tm_mday=25, tm_hour=8, tm_min=4, tm_sec=8, tm_wday=1, tm_yday=237, tm_isdst=-1), 1)
>>> 
```
