### ISSUE TITLE
Unexpected struct_time flag with Calendar.parse on HTML <a href> string

### ISSUE THREAD

**Issue by thadguidry** [bear/parsedatetime#66]
I was expecting a 0 instead of a 2 for the struct_time flag.

```
import parsedatetime
cal = parsedatetime.Calendar
print cal.parse('<a data-navid="792" href="/departments/departments-n-z/probate/estates-trusts/transfer-by-affidavit-50-000-and-under">')
```
OUTPUT:
((2014, 12, 2, 0, 0, 0, 1, 336, -1), 2)

**Comment by idpaterson** [comment]
This was recently fixed and will be included in the next release. Units such as hours are only picked out as standalone words like *792 hours* or attached to the number like *792h*. "792 href" in your example will no longer parse as a date. Since the parsing is done with regular expressions, the word boundary `\b` is used to ensure that the keyword is not just a substring in a larger word.

There were a lot of cases like this, we should be in much better shape now!

**Comment by thadguidry** [comment]
Awesome!  Thanks @idpaterson and @bear
