### ISSUE TITLE
composed negative relative timedelta

### ISSUE THREAD

**Issue by tigran-a** [bear/parsedatetime#79]
Hi,
Thanks for this cool library!

Tested what is the date three days one hour and 20 min ago, but..
```
In [1]: from parsedatetime import Calendar
In [2]: c = Calendar()
In [3]: c.parse("")
Out[3]: 
(time.struct_time(tm_year=2015, tm_mon=1, tm_mday=24, tm_hour=22, tm_min=42, tm_sec=33, tm_wday=5, tm_yday=24, tm_isdst=0),
 0)
In [4]: c.parse("3 days 1 hour 20 min ago")
Out[4]: 
(time.struct_time(tm_year=2015, tm_mon=1, tm_mday=22, tm_hour=0, tm_min=3, tm_sec=6, tm_wday=3, tm_yday=22, tm_isdst=-1),
 3)
In [5]: c.parse("3 days ago 1 hour ago 20 min ago")
Out[5]: 
(time.struct_time(tm_year=2015, tm_mon=1, tm_mday=21, tm_hour=21, tm_min=23, tm_sec=16, tm_wday=2, tm_yday=21, tm_isdst=-1),
 1)
```
Is it the expected behaviour? 

Thanks!

**Comment by bear** [comment]
Marking this as working as expected.

The reason this happens is that "ago" can only be linked to the "20 min" phrase so it will only adjust that phrase as a negative offset instead of the entire phrase.

I've always wanted to add/enhance parsedatetime to build a nlp graph of the phrase that it's parsing so that modifiers can be associated with each discrete piece but that hasn't happened yet.
